# Generated by Django 2.2.5 on 2019-11-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedtable',
            name='Class_Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.ClassRoom'),
        ),
        migrations.AddField(
            model_name='approvedtable',
            name='Select_Batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Batch'),
        ),
        migrations.AddField(
            model_name='approvedtable',
            name='Select_Trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Trainer'),
        ),
    ]
