# Generated by Django 2.2.5 on 2019-11-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191101_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedtable',
            name='Select_Trainer',
        ),
    ]
