# Generated by Django 2.2.5 on 2019-11-01 12:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_Name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=256)),
                ('Topic', models.CharField(max_length=256)),
                ('Date', models.DateField(default=datetime.datetime.now)),
                ('FeedBack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsp.FeedbackOP')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsp.Status')),
                ('Trainer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Trainer')),
            ],
        ),
    ]
